/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 1500 #1500
    gain: 12.0 #12

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.03
    light.max_ratio: 0.40
    light.max_angle: 20.0
    light.min_length: 15
    light.min_fill_ratio: 0.7
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.7
    ignore_classes: ["negative"]

    target_brightness_global: 40.0  # 目标亮度值 
    target_brightness_armor:  100.0  # 目标亮度值
    Kp: 0.01                 # 比例系数
    Ki: 0.0                  # 积分系数
    Kd: 0.001                # 微分系数
    Use_AAG: false       # 是否使用 Adaptive Adjustment of Gain

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.06 #0.06
      sigma2_q_yaw: 7.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.6
      max_match_yaw_diff: 0.6 #0.6

      tracking_thres: 5 #5
      lost_time_thres: 0.7
